### ISSUE TITLE
Rotten Tomatoes and Metacritic

### ISSUE THREAD

**Issue by alfablac** [campanflaviu/plexius#10]
First thanks for creating this app that supports Web 3.0

I saw a bunch of pics of the app and they all show Rotten Tomatoes and Metacritic ratings, but they don't show up on my end. Is there something I need to do or the support for these two aggregators was lost?

**Comment by campanflaviu** [comment]
Rotten Tomatoes and Metacritic ratings were based on the Freebase agent for Plex. I can't seem to find this agent anymore, maybe it's not supported. For now, Plexius has only IMDB and Trakt.tv ratings. Maybe will add more, but not in the near future
