### ISSUE TITLE
trailers

### ISSUE THREAD

**Issue by Salvationdk** [campanflaviu/plexius#3]
i only get these options 

 IMDB Ratings   Trakt.tv Ratings   YouTube Trailer

but i cannot see trailers, nor the trackt trailers.

**Comment by campanflaviu** [comment]
The youtube trailers are taken form the Trakt api. However I noticed that some movies are not having trailers.
It should appear on the left side of the play button from the toolbar.

![screen shot 2017-03-17 at 3 33 50 pm](https://cloud.githubusercontent.com/assets/5280013/24045280/2f4ddad8-0b27-11e7-80dd-b7e8b5db7ea5.png)

**Comment by Salvationdk** [comment]
![image](https://cloud.githubusercontent.com/assets/2484640/24046010/4b9ba2e8-0b21-11e7-95ef-19e9ee48c5db.png)

ok i see for this movie, but there is no trakt icon nor imdb. trailer is working..

**Comment by campanflaviu** [comment]
I'll take a look at this movie and try to fix it.



În vin., 17 mar. 2017 la 15:52, Salvationdk <notifications@github.com> a
scris:

**Comment by Salvationdk** [comment]
nvm i found out.
it was not loaded .. had to refresh the page.
the other trailer icon was from another addon, 
wich pulls from traileraddict via imdb link

https://github.com/piplongrun/TrailerAddict.bundle

**Comment by Salvationdk** [comment]
![image](https://cloud.githubusercontent.com/assets/2484640/24046247/3221c17a-0b22-11e7-8802-2c773279a380.png)

now it show correctly. the first trailer icon is from you, the second one is from the other bundle scraper.

**Comment by Salvationdk** [comment]
maybe you should search the imdb link for trailers? 
http://www.traileraddict.com/trailerapi

**Comment by campanflaviu** [comment]
I'll take a look at this one too. I can embed the video on the Trakt version if that's better. If traileraddict api doesn't have a better movie discovery, I incline to use Trakt instead since it's giving me the youtube trailer url from the same api call where I'm getting the rating.
