### ISSUE TITLE
[Request]Data graphs

### ISSUE THREAD

**Issue by pascalo7** [campanflaviu/plexius#5]
Could the graphs from Transmogrify be added to Plexius, it was a really cool feature and there is nothing else out there that i can find that does it.

**Comment by campanflaviu** [comment]
Sure! as soon as I make the current version stable, I will start working on it.

**Comment by Mushin** [comment]
Thanks, looking forward to this.

**Comment by 29z** [comment]
Thanks for adding this enhancement. It looks like the movies section needs to be tweaked somewhat though? example what mine currently looks like 

https://i.imgur.com/ybetaiX.png

as well as the added over time graph

https://i.imgur.com/wsfwuwh.png

the tv sections is displaying as usual

https://i.imgur.com/O6lMmzL.png and https://i.imgur.com/Of7Pcxp.png

Is anyone else having this problem? Is there anyway to fix this? Thanks
